apiVersion: v1
kind: Service
metadata:
  name: example-service-cpu
spec:
  selector:
    app: example-service-cpu
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
